### ISSUE TITLE
Slottable support?

### ISSUE THREAD

**Issue by ceopaludetto** [roninoss/rn-primitives#14]
In radix there's a Slottable component to be used with Slot which allow sibling components inside the slot (https://www.radix-ui.com/primitives/docs/utilities/slot#basic-example). It would be awesome to use in RN as well

**Comment by mrzachnugent** [comment]
@ceopaludetto Like this https://github.com/roninoss/rn-primitives/blob/main/packages/slot/src/slot.tsx ?

**Comment by ceopaludetto** [comment]
No, like this:
![image](https://github.com/roninoss/rn-primitives/assets/30508218/49886cf7-90c5-42c9-b4bd-80b0f5dfaf11)

In a normal slot like below, if you use asChild prop, you are not allowed to have inner content (eg an Icon):
```tsx
export function Component({ asChild, children }) {
  const As = asChild ? Slot : "button";
  
  return <As><SomeIcon />{children}</As>
}
```

This will cause a children array which is not allowed (since the Slot relies in the `cloneElement` function). Then radix introduced `Slottable`, which is basically a simple fragment wrapper which is used to do something like this:

```tsx
export function Component({ asChild, children }) {
  const As = asChild ? Slot : "button";
  
  return <As><SomeIcon /><Slottable>{children}</Slottable></As>
}
```

Now you can use the component normally, because if you use `asChild` then the Slottable children will be cloned and not the Slot children itself

**Comment by mrzachnugent** [comment]
Unfortunately, we will not be adding this feature.
