### ISSUE TITLE
ClassNames do not work on Nextjs

### ISSUE THREAD

**Issue by a-eid** [roninoss/rn-primitives#17]
it's open by default and some styles are not applied correctly. it works fine on android & ios however.

**Comment by megacherry** [comment]
same here

**Comment by mrzachnugent** [comment]
@a-eid Which styles are not applied correctly?

**Comment by megacherry** [comment]
hi @mrzachnugent,

as already written in the discord, packages like select or dropdown-menu do not seem to translate the classNames. In your showcase it looks fine, but in a monorepo (or standalone project) with nextjs it doesn't work.

e.g. select in your showcase (https://rnr-showcase.vercel.app/select):

```
<button dir="ltr" aria-autocomplete="none" aria-controls="radix-:r5:" aria-expanded="false" role="button" tabindex="0" class="css-175oi2r r-1loqt21 r-1otgn73 flex flex-row h-10 native:h-12 items-center text-sm justify-between rounded-md border border-input bg-background px-3 py-2 web:ring-offset-background text-muted-foreground web:focus:outline-none web:focus:ring-2 web:focus:ring-ring web:focus:ring-offset-2 [&amp;>span]:line-clamp-1 w-[250px]" type="button" data-state="closed"><span style="pointer-events: none;"><div dir="auto" class="css-146c3p1 text-sm native:text-lg text-popover-foreground native:text-base web:group-focus:text-accent-foreground">Apple</div></span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="text-foreground opacity-50"><path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="m6 9 6 6 6-6" aria-hidden="true" class="text-foreground opacity-50"></path></svg></button>
```

in my nextjs example (https://github.com/megacherry/nextjs-rnr):

```
<button dir="ltr" aria-autocomplete="none" aria-controls="radix-:R2km:" aria-expanded="false" role="button" tabindex="0" class="css-view-175oi2r r-cursor-1loqt21 r-touchAction-1otgn73" type="button" data-state="closed"><span style="pointer-events:none"><div dir="auto" class="css-text-146c3p1">Apple</div></span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="text-foreground opacity-50"><path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="m6 9 6 6 6-6" aria-hidden="true" class="text-foreground opacity-50"></path></svg></button>
```

As you can see, the classNames are not taken over by tailwind, although they are defined in the select component.

Thanks for taking the time to watch.

**Comment by a-eid** [comment]
> @a-eid Which styles are not applied correctly?


```tsx
<SelectPrimitive.Overlay style={[StyleSheet.absoluteFill, {backgroundColor: "#00000050"}]} >
```

**Comment by mrzachnugent** [comment]
> > @a-eid Which styles are not applied correctly?
> 
> ```tsx
> <SelectPrimitive.Overlay style={[StyleSheet.absoluteFill, {backgroundColor: "#00000050"}]} >
> ```

The Select component was updated to version `1.0.4` which fixes this issue

**Comment by a-eid** [comment]
@mrzachnugent perfect, thank you. will be testing it later today.

**Comment by mrzachnugent** [comment]
This is a Nextjs/webpack issue, it works in an expo project with react-native-web.

It seems that the classNames are not being added to react-native-web components from the `/node_modules` which seems like a bundler issue.

For example, a primitive with this testing style attribute will work: 
```jsx
<DropdownMenuPrimitive.Trigger style={{ $$css: true, test: "bg-blue-500" }} >{/* ... */}</DropdownMenuPrimitive.Trigger>
``` 
Whereas using `className="bg-blue-500"` will not work.

Currently investigating.

**Comment by w7tf** [comment]
@mrzachnugent 

I am experiencing the same issue but for expo (no nextjs, no expo web, native only) in a mono repo. Components such as Button, Badge and Text are working fine. Dropdown & Select are not working. Portal (root layout) was added, nativewind is working. 

Tried your starter, it works there. I tried finding the issue but I can't seem to find it.

**Comment by w7tf** [comment]
> @mrzachnugent
> 
> I am experiencing the same issue but for expo (no nextjs, no expo web, native only) in a mono repo. Components such as Button, Badge and Text are working fine. Dropdown & Select are not working. Portal (root layout) was added, nativewind is working.
> 
> Tried your starter, it works there. I tried finding the issue but I can't seem to find it.
> 
> ![image](https://private-user-images.githubusercontent.com/53350046/352668545-1f85aa84-318b-4f29-9542-88c7eb8cef88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjk5MTAsIm5iZiI6MTcyMjI2OTYxMCwicGF0aCI6Ii81MzM1MDA0Ni8zNTI2Njg1NDUtMWY4NWFhODQtMzE4Yi00ZjI5LTk1NDItODhjN2ViOGNlZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2MTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YWM1YTA5NzFmOWFiOGViYWRmZGYwYmMzYTFiY2EzNzYxZmVhZjFjNzg0ZDlkZDFmNTBjYzI1YjY2ZThkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_nE3GqMioZsENNLd4zYcFWuHdyk67LNvWzUZpmU_H0) The button with the text "Open" is the drop down.

This probably won't help the nextjs users that are experiencing issues, but it might help users that are using the library in a mono repo setup. 
In my case I had to add the following to metro config: 
config.resolver.disableHierarchicalLookup = true;

Issue link: https://github.com/nativewind/nativewind/issues/734

**Comment by megacherry** [comment]
> This is a Nextjs/webpack issue, it works in an expo project with react-native-web.
> 
> It seems that the classNames are not being added to react-native-web components from the `/node_modules` which seems like a bundler issue.
> 
> For example, a primitive with this testing style attribute will work:
> 
> ```js
> <DropdownMenuPrimitive.Trigger style={{ $$css: true, test: "bg-blue-500" }} >{/* ... */}</DropdownMenuPrimitive.Trigger>
> ```
> 
> Whereas using `className="bg-blue-500"` will not work.
> 
> Currently investigating.

@mrzachnugent: Do you know a workaround for this?

**Comment by qhoarau** [comment]
> This is a Nextjs/webpack issue, it works in an expo project with react-native-web.
> 
> It seems that the classNames are not being added to react-native-web components from the `/node_modules` which seems like a bundler issue.
> 
> For example, a primitive with this testing style attribute will work:
> 
> ```js
> <DropdownMenuPrimitive.Trigger style={{ $$css: true, test: "bg-blue-500" }} >{/* ... */}</DropdownMenuPrimitive.Trigger>
> ```
> 
> Whereas using `className="bg-blue-500"` will not work.
> 
> Currently investigating.

I have the same issue and writing as you said $$css: true, test: "bg-blue-500" works but className doesnt work. Did you find a solution ?

**Comment by mrzachnugent** [comment]
As a work around, you can copy the primitives into your ~/components/primitives. There's manual instructions on https://rnprimitives.com/

Then in your ~/components/ui files use the import from ~/components/primitives instead of @rn-primitives

The devs working on NativeWind have a lot of stuff going on so hopefully after the official release of v4, they'll be able to look into it.

**Comment by mrzachnugent** [comment]
They do now! You can update your primitives to their latest versions to get it to work with nextjs.

**Comment by francois-pasquier** [comment]
Sorry for bumping this closed issue but how are you guys using rn reusables with basic block like https://github.com/mrzachnugent/react-native-reusables/blob/main/packages/reusables/src/components/ui/text.tsx using createContext?

Sure, we could remove this but most of the components are using contexts so we need to add "use client"

**Comment by mrzachnugent** [comment]
@francois-pasquier, on the web text class names cascade so if you're project is only a Nextjs you don't need the `TextClassContext`.

Otherwise, you will need to use `"use client";` in all the components that want to pass a className through the `TextClassContext`. All of the `@rn-primitives/*` packages have the `"use client";` directive so if you are using react-native-reuables, it mostly just adds class names to those primitives. This means that adding another `"use client";` doesn't really change the rendering method in Nextjs. 

Alternatively, there's probably a way to make only native use createContext. For example, you can have a custom component like `text-class-provider.web.tsx` and `text-class-provider.tsx` where the web version returns a fragment. Then, `text.web.tsx` and a `text.tsx` where the web version doesn't use context. All react-native-web components use `"use client";` including the Text so your custom `text.web.tsx` would need to use html elements. And you would have to manually map the props, you couldn't use `SlottableTextProps` like in your link example.
