### ISSUE TITLE
[ BUG ] Component's className is not applied for frameworkless React Native projects

### ISSUE THREAD

**Issue by kaichaosun** [roninoss/rn-primitives#18]
The root of the cause is not clear, also create one here and link to upstream issue, not sure if it's related to nativewind,
https://github.com/mrzachnugent/react-native-reusables/issues/180

**Comment by mrzachnugent** [comment]
Closed due to: https://github.com/mrzachnugent/react-native-reusables/issues/180#issuecomment-2217785645
