### ISSUE TITLE
Bug: Checkbox not visible

### ISSUE THREAD

**Issue by ogzcode** [roninoss/rn-primitives#22]
Hi, 
I took the Checkbox example from the doc page and pasted it directly but nothing appears on the screen.
Also there are no printables

Screenshot:
![image](https://github.com/user-attachments/assets/876859d9-34fa-4028-83e0-dc79c0d9945d)

**Comment by mrzachnugent** [comment]
@ogzcode Looks like a NativeWind caching issue at first glance. Can you try restarting the app with `npx expo start --clear`?

If that doesn't fix it, can you provide a minimal reproduction repo? Otherwise, I won't be able to help
