### ISSUE TITLE
Open prop is missing in Popover

### ISSUE THREAD

**Issue by mohamedamara1** [roninoss/rn-primitives#33]
'open' prop is missing in the Popover root

**Comment by mohamedamara1** [comment]
My fault, the issue is not with this repo, it's with the react-native-reusables

**Comment by mrzachnugent** [comment]
@mohamedamara1 the prop is intentionally left out. Here is the reason why and how to go around it: https://rnr-docs.vercel.app/getting-started/common-patterns/#programmatically-showing-and-hiding-components

**Comment by mohamedamara1** [comment]
Got it, thank you

**Comment by danieldunderfelt** [comment]
@mrzachnugent the explanation is now a 404, but I am really scratching my head as to what can POSSIBLY be the reason. I _always_ need to control popover open/closed states, and omitting this is baffling.
