### ISSUE TITLE
Usage of typeScript types in components

### ISSUE THREAD

**Issue by fxamauri** [roninoss/rn-primitives#34]
Hi, I'm using the @rn-primitives/dialog package  and noticed that the TypeScript types are not being exported.

Could you clarify the correct way to access the type props of each component? Is there an issue with type exports, or should a different approach be used in TypeScript?

Additionally, could we consider exporting these types for easier use? I'd be happy to help with this if needed. 

Example:

```tsx
//example export - packages/dialog/src/dialog.tsx
export { Close, Content, Description, Overlay, Portal, Root, Title, Trigger, useRootContext };

export type { DialogContentProps, DialogOverlayProps, DialogPortalProps,  DialogRootProps, RootContext }
```

**Comment by NotSimple** [comment]
+1 to this. I'm currently getting typescript errors when trying to use some of the primitives when the types are not being exported. For example when using the label primitive:
` The inferred type of 'Label' cannot be named without a reference to '../../../node_modules/@rn-primitives/label/dist/types-BMNgdL5Y'. This is likely not portable. A type annotation is necessary`

**Comment by divineniiquaye** [comment]
I was getting this same error, it has to do with your tsconfig settings, I fixed mine by removing my jsx import source and changing node resolution to esnext

**Comment by mrzachnugent** [comment]
Typescript types are now being exported in the latest versions of the primitives
