### ISSUE TITLE
List - A very important component

### ISSUE THREAD

**Issue by modbender** [roninoss/rn-primitives#35]
I think this is a very basic component for every react native UI library and should be implemented with priority

![image](https://github.com/user-attachments/assets/0fa5e4fb-b81a-4352-9e7b-a622ee8e01b2)
-----
![image](https://github.com/user-attachments/assets/91ba9afa-57cc-45e0-94c9-9ad59d2ccd43)

Example is here:
https://mui.com/material-ui/react-list/

Especially this part:
https://mui.com/material-ui/react-list/#list-controls

Has a lot of use cases: 
- Settings page
- Listing out item or file properties
- Nested/collapsible list
- Editable list (edit properties of an item or file)
- Selectable list (file browsers or actions on multiple items)
- Pressable list
- List with switches
- and more

**Comment by mrzachnugent** [comment]
@modbender fortunately/unfortunately primitives for lists already exist with react-native so we will not be implementing one.
