### ISSUE TITLE
TooltipProvider is missing in tooltip primitive

### ISSUE THREAD

**Issue by megacherry** [roninoss/rn-primitives#43]
I wanted to use the new sidebar from shadcn and saw that the TooltipProvider is missing in the tooltip primitive.

I don't know if it's a limition or should the primitives be identical to radix?

**Comment by mrzachnugent** [comment]
Hey @megacherry the `TooltipProvider` from radix-ui is included in the `TooltipPrimitive.Root` from rn-primitives. You can checkout https://github.com/roninoss/rn-primitives/blob/main/packages/tooltip/src/tooltip.web.tsx#L47 to see how it is implement.

So it should work the same way without the need of using `TooltipProvider` yourself.
